"""Tests for the skill authoring system (Path 2 — operator describes, agent writes)."""

from unittest.mock import AsyncMock, MagicMock, patch

import pytest

from cognitex.agent.skill_authoring import (
    SkillAuthoring,
    SkillDraft,
    SkillTestResult,
    _slugify,
    _strip_code_fences,
)

# ---------------------------------------------------------------------------
# Fixtures
# ---------------------------------------------------------------------------

VALID_SKILL_CONTENT = """\
---
name: test-generated
description: A test skill generated by AI.
version: 1.0.0
metadata:
  cognitex: {}
---

# Test Generated

## Purpose
Test skill for unit tests.

## What IS
- Test input

## What is NOT
- Not a test

## Rules
1. Always pass tests

## Examples

### Example 1
Input: hello
Output: world
"""


@pytest.fixture
def mock_llm():
    """Mock LLM service that returns valid skill content."""
    llm = MagicMock()
    llm.complete = AsyncMock(return_value=VALID_SKILL_CONTENT)
    llm.fast_model = "test-model"
    return llm


@pytest.fixture
def mock_loader():
    """Mock skill loader."""
    loader = MagicMock()
    loader.save_skill = AsyncMock(return_value=True)

    # Mock get_skill for reference loading
    mock_skill = MagicMock()
    mock_skill.raw_content = "# Reference skill content"
    loader.get_skill = AsyncMock(return_value=mock_skill)

    return loader


@pytest.fixture
def authoring(mock_llm, mock_loader):
    """SkillAuthoring with mocked dependencies."""
    sa = SkillAuthoring.__new__(SkillAuthoring)
    sa._llm = mock_llm
    sa._loader = mock_loader
    return sa


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def test_slugify_basic():
    assert _slugify("Email Task Extraction") == "email-task-extraction"


def test_slugify_special_chars():
    assert _slugify("My Skill! v2.0") == "my-skill-v20"


def test_slugify_truncates():
    result = _slugify("a" * 100)
    assert len(result) <= 50


def test_strip_code_fences():
    text = "```yaml\n---\nname: foo\n---\n```"
    assert _strip_code_fences(text) == "---\nname: foo\n---"


def test_strip_code_fences_no_fences():
    text = "plain text"
    assert _strip_code_fences(text) == "plain text"


# ---------------------------------------------------------------------------
# create_from_description
# ---------------------------------------------------------------------------


@pytest.mark.asyncio
async def test_create_from_description(authoring, mock_llm):
    """Should generate a valid SkillDraft with parseable frontmatter."""
    draft = await authoring.create_from_description(
        description="Extract tasks from Slack messages",
    )

    assert isinstance(draft, SkillDraft)
    assert draft.name == "test-generated"  # from frontmatter
    assert draft.description == "A test skill generated by AI."
    assert "## Rules" in draft.content
    assert draft.version == 1
    assert draft.status == "draft"

    # LLM was called
    mock_llm.complete.assert_called_once()


@pytest.mark.asyncio
async def test_create_with_explicit_name(authoring, mock_llm):
    """Explicit name is passed to the prompt template."""
    draft = await authoring.create_from_description(
        description="Test",
        name="my-custom-skill",
    )

    # The prompt should contain the explicit name
    call_args = mock_llm.complete.call_args
    assert "my-custom-skill" in call_args.kwargs.get("prompt", call_args[1].get("prompt", ""))


@pytest.mark.asyncio
async def test_create_with_examples(authoring, mock_llm):
    """Examples should be included in the LLM prompt."""
    draft = await authoring.create_from_description(
        description="Test skill",
        examples=["Input: hello -> Output: hi", "Input: bye -> Output: goodbye"],
    )

    call_args = mock_llm.complete.call_args
    prompt = call_args.kwargs.get("prompt", call_args[1].get("prompt", ""))
    assert "hello" in prompt
    assert "goodbye" in prompt


# ---------------------------------------------------------------------------
# refine_draft
# ---------------------------------------------------------------------------

REFINED_CONTENT = """\
---
name: test-generated
description: A refined test skill.
version: 1.0.1
metadata:
  cognitex: {}
---

# Test Generated (Refined)

## Purpose
Refined purpose.

## Rules
1. Updated rule
"""


@pytest.mark.asyncio
async def test_refine_increments_version(authoring, mock_llm):
    """Refining should increment the version number."""
    mock_llm.complete = AsyncMock(return_value=REFINED_CONTENT)

    draft = SkillDraft(
        name="test-generated",
        description="original",
        content=VALID_SKILL_CONTENT,
        version=1,
    )
    refined = await authoring.refine_draft(draft, "Make it shorter")

    assert refined.version == 2
    assert "Updated rule" in refined.content


@pytest.mark.asyncio
async def test_refine_appends_feedback(authoring, mock_llm):
    """Feedback history should grow with each refinement."""
    mock_llm.complete = AsyncMock(return_value=REFINED_CONTENT)

    draft = SkillDraft(
        name="test",
        description="",
        content=VALID_SKILL_CONTENT,
        version=1,
        feedback_history=["first feedback"],
    )
    refined = await authoring.refine_draft(draft, "second feedback")

    assert len(refined.feedback_history) == 2
    assert refined.feedback_history[-1] == "second feedback"


# ---------------------------------------------------------------------------
# test_skill
# ---------------------------------------------------------------------------


@pytest.mark.asyncio
async def test_test_skill_returns_results(authoring, mock_llm):
    """Test skill should return results with success=True for valid output."""
    mock_llm.complete = AsyncMock(return_value="Extracted task: Review PR")

    draft = SkillDraft(name="test", description="", content=VALID_SKILL_CONTENT)
    results = await authoring.test_skill(draft, ["Check out the latest PR"])

    assert len(results) == 1
    assert isinstance(results[0], SkillTestResult)
    assert results[0].success is True
    assert "Review PR" in results[0].output_text
    assert draft.status == "tested"


@pytest.mark.asyncio
async def test_test_skill_parse_error(authoring, mock_llm):
    """Empty/malformed content should produce a failed test result."""
    draft = SkillDraft(name="broken", description="", content="")
    results = await authoring.test_skill(draft, ["some input"])

    assert len(results) == 1
    assert results[0].success is False
    assert results[0].error is not None


@pytest.mark.asyncio
async def test_test_skill_llm_error(authoring, mock_llm):
    """LLM errors during testing should be caught as failed results."""
    mock_llm.complete = AsyncMock(side_effect=RuntimeError("API error"))

    draft = SkillDraft(name="test", description="", content=VALID_SKILL_CONTENT)
    results = await authoring.test_skill(draft, ["input"])

    assert len(results) == 1
    assert results[0].success is False
    assert "API error" in results[0].error


# ---------------------------------------------------------------------------
# deploy_skill
# ---------------------------------------------------------------------------


@pytest.mark.asyncio
async def test_deploy_saves_to_user_dir(authoring, mock_loader):
    """Deploy should call save_skill and update status."""
    draft = SkillDraft(name="my-skill", description="", content=VALID_SKILL_CONTENT)

    with patch("cognitex.agent.action_log.log_action", new_callable=AsyncMock):
        success = await authoring.deploy_skill(draft)

    assert success is True
    mock_loader.save_skill.assert_called_once_with("my-skill", VALID_SKILL_CONTENT)
    assert draft.status == "deployed"


@pytest.mark.asyncio
async def test_deploy_failure(authoring, mock_loader):
    """Deploy failure should return False and not update status."""
    mock_loader.save_skill = AsyncMock(return_value=False)

    draft = SkillDraft(name="fail", description="", content="content")
    success = await authoring.deploy_skill(draft)

    assert success is False
    assert draft.status == "draft"
